apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
  labels:
    role: frontend
    env: demo
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
        env: demo
    spec:
      containers:
        - name: frontend-app
          image: dilipford/frontend:latestt
          imagePullPolicy: Always  # Ensures the latest image is always pulled
          ports:
            - containerPort: 3000  # Change this to your frontend service port
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
